### ISSUE TITLE
integrate with uds-cli v0.0.6-alpha

### ISSUE THREAD

**Issue by timblaktu** [defenseunicorns/uds-idam#102]
Presumably introduced in #74 and recent changes in `uds-cli`, `make cluster/full` fails in the **Package Images** stage of the `build/bundle` target when using uds v0.0.6-alpha:

```
  📦 PACKAGE IMAGES
  ✔  Loading metadata for 4 images.
  ✔  Pulling 4 images (654.56 MBs)
  ✔  Creating SBOMs for 4 images and 2 components with files.
  ✔  Package tarball successfully written
cd dev && uds bundle create --set INIT_VERSION=v0.29.2 --set METALLB_VERSION=0.0.1 --set DUBBD_VERSION=0.9.0 --set IDAM
_VERSION=0.1.12 --confirm
Error: unknown flag: --set
```

Looks like the recipe:

```
build/bundle: | build
        cd dev && uds bundle create --set INIT_VERSION=$(ZARF_VERSION) --set METALLB_VERSION=$(METALLB_VERSION) --set DUBBD_VERSION=$(DUBBD_K3D_VERSION) --set IDAM_VERSION=$(IDAM_VERSION) --confirm
```

needs changed to use the latest uds-cli incantation for building a bundle:

```
[0]tim@thinky:~/src/du/uds-idam > uds help bundle create                                            uds-idam (main) %

 NOTE  Saving log file to /tmp/uds-2023-10-18-11-51-49-264430243.log
Create a bundle from a given directory or the current directory

Usage:
  uds bundle create [DIRECTORY] [flags]

Aliases:
  create, c

Flags:
  -c, --confirm                       REQUIRED. Confirm the removal action to prevent accidental deletions
  -h, --help                          help for create
  -o, --output string                 Specify the output (an oci:// URL) for the created bundle
  -k, --signing-key string            Path to private key file for signing bundles
  -p, --signing-key-password string   Password to the private key file used for signing bundles

Global Flags:
      --insecure              Allow access to insecure registries and disable other recommended security enforcements such as package checksum and signature validation. This flag should only be used if you have a specific reason and accept the reduced security posture.
  -l, --log-level string      Log level when running UDS-CLI. Valid options are: warn, info, debug, trace (default "info")
      --no-log-file           Disable log file creation
      --no-progress           Disable fancy UI progress bars, spinners, logos, etc
      --oci-concurrency int   Number of concurrent layer operations to perform when interacting with a remote bundle. (default 3)
      --tmpdir string         Specify the temporary directory to use for intermediate files
      --zarf-cache string     Specify the location of the Zarf cache directory (default "~/.zarf-cache")
```

**Comment by timblaktu** [comment]
Brief chat with @rjferguson21 and then @UncleGedd, and RTFM on `uds-cli` main, lead me to the solution I will be committing shortly, which:

1. removes the deprecated `--set` args from `uds create`
2. change references to the deprecated `###BNDL_TMPL_*###` vars to use shell var syntax `${SOME_VAR}`
3. fix naming of make variable constants in Makefile and export them to subshells
4. `mv dev/uds-bundle.yaml dev/uds-bundle.yaml.tmpl`
5. modify build/bundle recipe to render `dev/uds-bundle.yaml` from `dev/uds-bundle.yaml.tmpl` using `envsubst`, before calling `uds create`

With all this, I'm getting a lot further now, only stunted by an authZ error when Validating thet init package in uds bundle.. 

```
  ⠹  Validating Bundle Package: init (0s)
     ERROR:  Failed to create bundle: HEAD
             "https://ghcr.io/v2/defenseunicorns/packages/init/manifests/v0.29.2-amd64": response status code
             401: Unauthorized
```

**Comment by timblaktu** [comment]
Pulling the zarf init pkg at the cmd line (outside the uds bundle build), via `zarf package download-init` works fine, with no changes to AuthN/Z. I have deleted my k3d clusters and reproduced the issue from scratch. For me this is easily reproduced using this branch, `zarf v0.29.2` and `uds v0.0.6-alpha`, and  otherwise following the README instructions, running `make cluster/full`.

**Comment by timblaktu** [comment]
Earlier I reverted uds cli to previous release (0.0.5-alpha) and checked out main again and reran and _it just worked_. So @rjferguson21 @UncleGedd this appears to not only be a lack of support here in uds-idam for the latest uds-cli api, but there also is a bug in latest uds-cli that fails to validate a zarf init package when building a uds bundle. 

This is a "note to self" (and to @docandrew @Vandiver247 and @benmountjoy111) to make sure we're NOT using the latest uds cli in any attempts to integrate the uds-idam package tomorrow.

**Comment by UncleGedd** [comment]
Hey @timblaktu thanks for the report! I'd love to delve into this issue more, I'll reach out to yourself and @rjferguson21

**Comment by UncleGedd** [comment]
The latest version of UDS CLI uses 0.29.x under the hood. It _may_ be able to deploy the 0.30.x Zarf init pkg but it hasn't been tested. There is a [UDS CLI PR ](https://github.com/defenseunicorns/uds-cli/pull/123) to upgrade to the latest Zarf lib code internal to UDS CLI, hoping to have a release in the next day or so
