### ISSUE TITLE
Support for adding istio annotation to control LB placement in AWS

### ISSUE THREAD

**Issue by kirankt** [defenseunicorns/uds-idam#35]
e.g 
```
       serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-internal: "###ZARF_VAR_KEYCLOAK_PASSTHROUGH_LB###"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
```

**Comment by rjferguson21** [comment]
@kirankt https://github.com/defenseunicorns/uds-idam/pkgs/container/uds-capability%2Fuds-idam-aws is published and currently supports setting `PRIVATE_KEYCLOAK_LB` (https://github.com/defenseunicorns/uds-idam/blob/main/aws/zarf.yaml#L12-L14) which is true by default.
