### ISSUE TITLE
Auto update DUBBD OCI images and other dependencies

### ISSUE THREAD

**Issue by kirankt** [defenseunicorns/uds-idam#73]
Configure renovate to update the OCI images in the repo to the latest available.

e.g. github workflows are still referencing dubbd oci image version 0.3.0. The current version as of this moment, is 0.8.1

**Comment by rjferguson21** [comment]
@kirankt I believe as of https://github.com/defenseunicorns/uds-idam/pull/74 where we started using the Makefile for CI we should be tracking dependencies via renovate.  

Having said that I did notice when checking that it seems like something is specifically not working with k3d-dubbd.  It should have picked up the 0.9.1 tag so I opened this - https://github.com/defenseunicorns/uds-idam/issues/85

**Comment by rjferguson21** [comment]
This should be addressed.
