### ISSUE TITLE
Keycloak in crash loop

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-idam#79]
![image](https://github.com/defenseunicorns/uds-idam/assets/16000938/b8bd471a-0067-439a-8b3d-c6721bc17822)

it was working when I was using v0.1.9. Errors now with v0.1.11

PR where I'm making the change: https://github.com/defenseunicorns/narwhal-delivery-reference-deployment/pull/17

**Comment by RothAndrew** [comment]
Confirmed v0.1.9 works against the same setup. I tested it just now.

**Comment by RothAndrew** [comment]
Figured out why, postgres is now an external dependency, but the package doesn't install it. It has to be installed separately.

**Comment by UnicornChance** [comment]
@RothAndrew I believe this was already answered via slack. Cross posting for good measure.

I have a PR for updating the README for more information about our recent change of not including the original in-cluster postgres DB. Working with SWF and their need for an external DB for gitlab etc. as well as the plan for a uds postgres capability, we exposed the [keycloak variables for connecting to an external DB](https://github.com/defenseunicorns/uds-idam/blob/main/idam/zarf.yaml#L58-L72). However, the original postgres DB can still be enabled and installed by [setting this value](https://github.com/defenseunicorns/uds-idam/blob/main/idam/zarf.yaml#L58-L59) to `true`.
